export const keyValues = {

    "Avertising  Network": "Advertising",
    "ads txt": "Advertising",
    "Ad Exchange": "Advertising",
    "Audience Targeting": "Advertising",
    "Facebook Exchange": "Advertising",
    "Ad Server": "Advertising",
    "Affiliate Programs": "Advertising",
    "Contextual Advertising": "Advertising",
    "Dynamic Creative Optimization": "Advertising",
    "Digital Video Ads": "Advertising",
    "Retargeting / Remarketing": "Advertising",
    "Header Bidding": "Advertising",

    "Application Performance": "Analytics and Tracking",
    "A/B Testing": "Analytics and Tracking",
    "Ad Analytics": "Analytics and Tracking",
    "Conversion Optimization": "Analytics and Tracking",
    "Advertiser Tracking": "Analytics and Tracking",
    "Tag Management": "Analytics and Tracking",
    "Audience Measurement": "Analytics and Tracking",
    "Visitor Count Tracking": "Analytics and Tracking",

    "Non Platform": "Ecommerce",
    "Hosted Solution": "Ecommerce",
    "Open Source": "Ecommerce",
    "Checkout Buttons": "Ecommerce",
    "Payment Acceptance": "Ecommerce",
    "Payments Processor": "Ecommerce",
    "Payment Currency": "Ecommerce",

    "Live Chat": "Widgets",
    "Login": "Widgets",
    "Ticketing System": "Widgets",
    "Bookings": "Widgets",
    "Social Sharing": "Widgets",
    "Schedule Management": "Widgets",

    "Cloud Hosting": "Hosting",
    "Cloud PaaS": "Hosting",
    "Dedicated Hosting": "Hosting",
    "Business Email Hosting": "Hosting",
    "Web Hosting Provider Email": "Hosting",
    "Marketing Platform": "Hosting",

    "CRM": "Productivity",
    "Lead Generation": "Productivity",
    "Marketing Automation": "Productivity",
    "Product Recommendations": "Productivity",
    "Feedback Forms and Surveys": "Productivity",
    "Campaign Management": "Productivity"
}